name: firebase_push_notification
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

# Dependencies
dependencies:
  code_text_field: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^0.13.5
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  flutter_styled_toast: ^2.1.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  # Material Icons
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/logos/

  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font.
  fonts:
    - family: SourceCodePro
      fonts:
        - asset: fonts/SourceCodePro-Regular.ttf
        - asset: fonts/SourceCodePro-Medium.ttf
        - asset: fonts/SourceCodePro-Bold.ttf
          style: normal
    - family: SourceCode
      fonts:
        - asset: fonts/SourceCodePro-Regular.ttf
          weight: 700
